name: thrive_quit_application
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.1.1
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.1
  google_maps_flutter : ^2.5.3
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  table_calendar: ^3.0.6
  expandable: ^5.0.1
  outline_gradient_button: ^2.0.0+1
  intl: ^0.18.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_ui_auth: ^1.12.1
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.2.17
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: DM Sans
      fonts: 
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
        - asset: assets/fonts/DMSansRegular.ttf
          weight: 400
        - asset: assets/fonts/DMSansMedium.ttf
          weight: 500
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
